apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  labels:
    app: guestbook
    tier: frontend
spec:
  type: "{{ .Values.serviceType }}"
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
